---
title: "V.\ Statistical analysis in R (solution)"
author: "Data Science Lab, University of Copenhagen"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  #pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
library(MASS)
library(emmeans)
```


## Data

```{r, message=FALSE, fig.height=3, fig.width=4}
### Open help page for birthwt
?birthwt

### Make a tibble with the data
birthData <- as_tibble(birthwt)
birthData

### Make smoke into a factor
# Check if `smoke` is numerical
is.numeric(birthData$smoke)
# Alternatively, review the summary of the whole dataset
summary(birthData)
# Finally, make smoke into a factor
birthData <- mutate(birthData, smoke = factor(smoke))

# Check the ftv variable, make it a factor and collapse some of the levels
table(birthData$ftv)
birthData <- mutate(birthData, ftvFac = factor(ftv))
birthData <- mutate(birthData, visits = fct_collapse(ftvFac, Never="0", Once="1", other_level="MoreThanOnce"))
summary(birthData)

### Parallell boxplots
ggplot(birthData, aes(x=visits, y=bwt)) + geom_boxplot() 
ggplot(birthData, aes(x=smoke, y=bwt)) + geom_boxplot() 
# Groupwise boxplots
ggplot(birthData, aes(x=smoke:visits, y=bwt, col=smoke)) + geom_boxplot() 

### Scatterplot
ggplot(birthData, aes(x=lwt, y=bwt)) + geom_point() 

### Scatter plot with points coloured after visits, and point types after smoke status
ggplot(birthData, aes(x=lwt, y=bwt, col=visits)) + geom_point() 
ggplot(birthData, aes(x=lwt, y=bwt, col=visits, pch=smoke)) + geom_point() 
```

## Regression

```{r}
### Simple linear regression
reg1 <- lm(bwt ~ lwt, data=birthData) 
summary(reg1)
confint(reg1)

### Model validation
par(mfrow=c(2,2))
plot(reg1)

### Include age and ftv as covariate
reg2 <- lm(bwt ~ lwt + age + ftv, data=birthData)
summary(reg2)
# Just to view the coefficients
summary(reg2)$coefficients

### Prediction
newData <- data.frame(lwt=100, age=25, ftv=0)
newData
predict(reg2, newData)
predict(reg2, newData, interval="prediction")

### Use only data from mothers with weight below 160
reg3 <- lm(bwt ~ lwt + age + ftv, data=filter(birthData, lwt<160))
summary(reg3)
# Just to view the coefficients
summary(reg3)$coefficients
```


## ANOVA

```{r}
### Oneway ANOVA against smoke
oneway1 <- lm(bwt ~ smoke, data=birthData)
summary(oneway1)
summary(oneway1)$coefficients
emmeans(oneway1,~smoke)
pairs(emmeans(oneway1,~smoke))

### Oneway ANOVA against visits
oneway2 <- lm(bwt ~ visits, data=birthData)
summary(oneway2)
emmeans(oneway2,~visits)
pairs(emmeans(oneway2,~visits))
drop1(oneway2,test="F")

### Twoway ANOVA without interaction
twoway1 <- lm(bwt ~ visits + smoke, data=birthData)
summary(twoway1)
summary(twoway1)$coefficients    

### Twoway ANOVA with interaction, test for interaction in two ways
twoway2 <- lm(bwt ~ visits * smoke, data=birthData)
summary(twoway2)
anova(twoway2, twoway1)
drop1(twoway2,test="F")
# Compute the expected birth weight of infants for smokers and non-smokers, respectively, on average over the three levels of `visits`
emmeans(twoway2, ~smoke)
```

## Models with numerical as well as categorical predictors

```{r}
### Model with linear (lwt,bwt) association. 
### Intercept differ between smokers and non-smokers, one common slope.
model1 <- lm(bwt ~ lwt + smoke, data=birthData)
summary(model1)

### Model with linear (lwt,bwt) association. Intercept and slope both differ between visit groups
model2 <- lm(bwt ~ lwt * smoke, data=birthData)
summary(model2)

### Test if slopes differ between visit groups
anova(model2, model1)

### Model with many effects (no interactions)
model3 <- lm(bwt ~ lwt + smoke + age + visits, data=birthData)
par(mfrow=c(2,2))
plot(model3)
summary(model3)
```

## Logistic regression

```{r}
### Logistic regression with many predictors (no interactions)
logreg1 <- glm(low ~ lwt + smoke + age + visits, data=birthData, family="binomial")
summary(logreg1)
```


## Linear mixed models

```{r}
### Make artificial center variable
set.seed(123)
center <- sample(rep(1:19, each=10)[1:189])
birthData <- mutate(birthData,center=factor(center))

### Remember to install lme4 before this can run
# install.packages("lme4")
library(lme4)

### Linear mixed model with random effect of center
lmm1 <- lmer(bwt ~ lwt + smoke + age + visits + (1|center), data=birthData)
summary(lmm1)
```


