### II. Working with data in R (R codes for presentation)

### See the files presentation2.html and presentation2.pdf for further explanations. 
### These files are generated by the Markdowm file presentation2.Rmd 


#############

### Set working directory 


# show current working directory
getwd()

# absolute path
setwd("~/Desktop/FromExceltoR/")

# relative path
setwd('./Presentations')

# go one step back in the directory
setwd('..')

# show folders in cwd
list.dirs(path = ".", recursive = FALSE)

#set working directory absolute path
setwd("/Users/kgx936/Desktop/FromExceltoR/Presentations")



############
### Tidyverse package 
#install.packages('tidyverse')
#install.packages('readxl')


# Load package
library(tidyverse)

# Load a package that can read excel files
library(readxl)

############

### Import data

# This command is generated via the Import data facility
downloads <- read_excel("downloads.xlsx")
downloads

###############

### Data structures

# Before we continue with tidyverse, lets look at some highly used data structures in R. 

#You will need to make structures or convert between these in R. 
#In the example below we will convert a tibble to a dataframe.

# Convert existing object to a dataframe:
downloads2 <-  as.data.frame(downloads)
head(downloads2) # head/top of object


#############

### Extracting variables, simple summary statistics

# Extract time variable by use of $ syntax
time_vector <- downloads$time
head(time_vector)


# Want to know what data type or structure you have, try the function class.
class(downloads)
class(downloads2)
class(time_vector)

# Get dimensions of your dataset
dim(downloads)


# First lines of dataset or vector on screen x[row, column]
downloads[1:5, 1:3]
time_vector[1:40]


# Simple summary statistics
length(time_vector)
mean(time_vector)
sd(time_vector)
median(time_vector)
min(time_vector)


###############

### Let's try some tidyverse commands.

###############



### Filtering data (selecting rows): filter
  
# see only datalines with time variable >1000
filter(downloads, time > 1000)

# great about tidyverse: write code the way you think
downloads %>% 
  filter(time > 1000) # processed from left to right

# my style: when assigning and doing multiple operations, use pipe operator
# also when it helps readability
# otherwise write as little as possible

# Only datalines with size variable >0
downloads3 <- downloads %>% 
  filter(size > 0)

# view data
downloads3 # print the first lines in console


# what are the unique machine names in downloads3?
distinct(downloads3, machineName)

# Datalines from kermit, and with size greater than 2000000 bytes are kept.
downloads3 %>% 
  filter(machineName == "kermit" & size > 2000000)

# other conditional operators can be found in the first presentation!
# or just google it

?dplyr::filter

# what if you want to filter multiple arguments in a variable?
downloads3 %>% 
  filter(machineName %in% c("kermit","pluto"), size > 2000000)

#############

### Selecting variables (columns): select

# Only include the three mentioned variable names
downloads4 <- downloads3 %>% 
  select(machineName, size, time)

downloads4

###############

### Transformations of data

# New variables included in dataset
downloads4 <- downloads4 %>% 
  mutate(speed = size/time ,logSize = log10(size))

downloads4

downloads4 <- downloads4 %>% 
  mutate(slow = ifelse(speed < 150, "Yes", "No"))

downloads4

?mutate
###########

### Counting, tabulation of categorical variables: count

# Total number of observations in the current dataset
count(downloads4)

# Number of observations from each machine
count(downloads4, machineName)

# Number of observations which have/have not size larger than 5000
count(downloads4, size>5000)

##########

## Sorting data: arrange

# Sort after size
arrange(downloads4, size)

# Sort according to download size in descending order
arrange(downloads4, desc(size))

# Sort after machine name and then according to download size in descending order
arrange(downloads4, machineName, desc(size))

#########

### Grouping: group_by
  
# Group according to machine
group_by(downloads4, machineName)

# Group according to machine and slow
group_by(downloads4, machineName, slow)

###########

### Summary statistics, revisited: summarize

# Method from above  
mean(downloads4$size)
max(downloads4$size)

# Group after machine name and make summaries for each machine
downloads4 %>%
  group_by(machineName) %>%
  summarise(avg = mean(size),
            med = median(size),
            stdev = sd(size),
            total = sum(size),
            n = n())


# Group after machine name and slow variable, and make summaries for each combination

downloads4 %>% 
  group_by(machineName, slow) %>%
  summarize(avg = mean(size),
            med = median(size),
            stdev = sd(size),
            total = sum(size),
            n = n())


##########

### The pipe operator: %>%

# Many commands combined with the pipe operator
# see that the variables for functions change, as the dataframe stands now at the beginning of the sequence

downloads %>% 
  filter(size > 0) %>% # Subset of data
  group_by(machineName) %>% # Grouping 
  summarize(avg = mean(size)) %>% # Compute mean
  arrange(avg) # Sort after mean


##########

### More dplyr functions from tidyverse

##########

# relocate (move one or more columns):
downloads %>% relocate(time, .before = size)

# rename (rename one column):
downloads %>% rename(year.month=month)

# pull out one column, equivalent to using $:
downloads %>% pull(machineName)


##########

# Join tibbles with subsets of information together:

# machineName and power rank
dowloads5 <- tibble(machineName=c("cs18","piglet","tweetie","kermit", "pluto"),
                    powerRank=c(2,4,1,3,5))
dowloads5


# machineName and location of machine
dowloads6 <- tibble(machineName=c("cs18","tweetie","kermit","skeeter"),
                    location=c("China", "USA", "Germany", "Japan"))
dowloads6


# all machineNames from tibble on the left are kept
left_join(dowloads5, dowloads6)

# all machineNames from tibble on the right are kept
right_join(dowloads5, dowloads6)

# only machineNames in both left and right tibble are kept 
inner_join(dowloads5, dowloads6)

# all machineNames, from both tibbles are kept
full_join(dowloads5, dowloads6)

