### I. The Fundamentals of R (R codes for presentation)
### Center for Health Data Science, University of Copenhagen

### See the files presentation1.html and presentation1.pdf for further explanations. 
### These files are generated by the Markdowm file presentation1.Rmd 

#############


### Working directory 



## The term 'path' refers to the trajectory you need to follow from the place 
## you are "located" on your computer to the place you want to work from. 
## As you will see below, a path can be either relative or absolute.


# set working directory (absolute path)
setwd("~/HeaDS/Courses/Excel_to_R/Mar_2023/FromExceltoR")

# where am I now?
getwd()

# set working directory (relative path)
setwd('./Presentations')



### Variable assignment

# In R we use an arrow for variable assignment. You may call your almost variables whatever you like.
# DO NOT: use special characters in variable names, i.e. &, ), $ etc. or make spaces in naming.


# A vector of numbers named num1
num1 <- c(5,1,11,6,4)
num1



### Functions & Arguments

## Function are chunks of code wrapped in a way which makes the code inside reusable. 
## A function takes an input(s) (arguments) and returns an output(s). 
## One concept example could be: 

# function(x,y) {
 # z <- x + y 
 # return(z)
# }


# Get the mean of some numbers:
(5+1+11+6+4)/5


# Or I use the function mean.
# x (which is some numbers/values) is the input argument and mean is the output. 
mean(num1)




# Functions makes code reusable:
num2 <- c(0,3,4,9,1,2,7,10,2,11)

mean(num2)
# or
mean(c(0,3,4,9,1,2,7,10,2,11))



# Using a function it is easy to get basic summary statistics on an object in R. 
# The R-base has a variety of simple stats functions build in (i.e. no package needs to be loaded):

# Simple summary statistics

length(num2)

sd(num2)
median(num2)
sum(num2)

min(num2)
max(num2)





############

### R packages 

## R packages are collections of functions written by R developers and super users and they make our lives much easier. 
## Functions used in the same type of R analysis/pipeline are bundled and organized in packages.
## There is a help page for each package to tell us which functions it contains and which arguments go into these.

# In order to use a package we need to download and install it on our computer. 
# Most R packages are stored and maintained on the CRAN[https://cran.r-project.org/mirrors.html] repository. 



# Install a package
# install.packages('tidyverse')



# Load package
library(tidyverse)

# Query package
?tidyverse

# Query function from package
?select()




# SLIDE BREAK




############

### Data Structures

## In the example below we will make two vectors into a tibble. 
## This are the R object types you will mainly be working with in this course.
## We will try to convert between data types and structures using the collection of 'as.' functions. 



# A vector of characters:
people <- c("Diana", "Tugce", "Gerardo", "Alex", "Inigo", "Valentina", "Sara")
people

# A vector of numeric values:
joined_year <- c(2020, 2020, 2022, 2021, 2021, 2022, 2023)
joined_year

############


# Want to know what data type or structure you have, try the function class.
class(people)
class(joined_year)


# Convert joined_year to character values
joined_year <- as.character(joined_year)
joined_year
class(joined_year)

# Convert cakeSlice back to numeric values
joined_year <- as.numeric(joined_year)
joined_year


# Other examples of 'as.' functions for type conversion:
# as.numeric()
# as.integer()
# as.character()
# as.factor()
# ...




############




# Lets make a tibble:

my_data <- tibble(name = people, 
                  joined_year = joined_year)
my_data
class(my_data)


# Just like you can convert between different data types, you can convert between data structures/objects:

# Convert tibble to dataframe:
as.data.frame(my_data)
class(my_data)

# Other examples of 'as.' function for structure/object conversion
# as.data.frame()
# as.matrix()
# as.list()
# as.table()
# ...
# as_tibble()






#############





### Fundamental operations 

# You can inspect an R objects in different ways:
    # 1. Simply call it and it will be printed to the console. 
    # 2. With large object it is preferable to use `head()` or `tail()` to only see the first or last part.
    # 3. To see the data in a tabular excel style format you can use `view()`

# Look at the "head" of an object, default is print first 6 lines:
head(my_data, n=8)

# Look at the "tail" of an object, default is print last 6 lines:
tail(my_data, n=8)

# opens table as a table, excel style
view(my_data)


# `dim()`, short for dimensions, which returns the number of rows and columns of an R object.

dim(my_data)


# Often we would like to pull out a single column from a dataframe or tibble to work with. 
# This may be done with the '$' symbol:

# Extract variable with $ symbol
my_data$joined_year

year <- my_data$joined_year
year


# Only interested in a specific subset of either rows or columns from an R data object?, use a 'slice'.
# A 'slice' is defined as square parentheses with the selection of rows/columns inside it. 


# Specific rows/columns of an R object (a slice):
my_data[1:5, 1:2]
my_data[, 1:2]

people[3:9]









