### I. The Fundamentals of R (R codes for presentation)

### See the files presentation1.html and presentation1.pdf for further explanations. 
### These files are generated by the Markdowm file presentation1.Rmd 

#############

### Working directory 



## The term 'path' refers to the trajectory you need to follow from the place you are "located" on your computer to the place you want to work from. 
## As you will see below, a path can be either relative or absolute.


# set working directory (absolute path)
setwd('/Users/kgx936/Desktop/HeaDS/GitHub_repos/FromExceltoR/Presentations')
setwd('~/Desktop/HeaDS/GitHub_repos/FromExceltoR/Presentations')

# move one directory back
setwd('..')

# where am I now?
getwd()

# set working directory (relative path)
setwd('./Presentations')

# show folders in wd
list.dirs(path = '.', recursive = FALSE)


############


### R packages

## R packages are collections of functions written by R developers and super users and they make our lives much easier. 
## Functions used in the same type of R analysis/pipeline are bundled and organized in packages.
## There is a help page for each package to tell us which functions it contains and which arguments go into these.

# In order to use a package we need to download and install it on our computer. 
# Most R packages are stored and maintained on the CRAN[https://cran.r-project.org/mirrors.html] repository. 



# Install a package
# install.packages('tidyverse')



# Load package
library(tidyverse)

# Query package
?tidyverse

# Query function from package
?select()
?dplyr::filter()
?mean()




# We can also unload a package from an R session:
  
detach('package:tidyverse') 
library(tidyverse)


# If we would like to remove a package we can do so with `remove.packages('')`. 
# N.B this will remove the package from your computer, not just from the R session.

#remove.packages('tidyverse')





# SLIDE BREAK




############

### Data Structures

## In the example below we will make some vectors, a tibble and a dataframe. These are the R object types you will mainly be working with in this course.
## We will try to convert between data types and structures using the collection of 'as.' functions. 



# A vector of characters:
groupMembers <- c("Diana", "Tugce", "Henrike", "Thilde", "Alex", "Jennie", "Viki", "Yuhu", "Inigo", "Jonas", "Conor", "Marilena", "Chloe", "Anders")
groupMembers

# A vector of integer values:
cakeDegrees <- c(44.67, 35.43, 30.13, 44.94, 45.0, 39.37, 32.79, 43.92, 44.61, 40.88, 32.28, 42.79, 39.17, 55.41)
cakeDegrees


# Want to know what data type or structure you have, try the function class.
class(cakeDegrees)
class(groupMembers)


# Convert cakeDegrees to character values
cakeDegrees <- as.character(cakeDegrees)
cakeDegrees

# Convert cakeDegrees back to numeric values
cakeDegrees <- as.numeric(cakeDegrees)
cakeDegrees

# Convert cakeDegrees to integer values (whole numbers)
cakeDegrees <- as.integer(cakeDegrees)
cakeDegrees


# Other examples of 'as.' functions for type conversion:
# as.numeric()
# as.integer()
# as.character()
# as.factor()
# ...









# Lets make some data structures:

# Make a dataframe
CakeDF <- data.frame(groupMembers = groupMembers, 
           cakeDegrees = cakeDegrees)

# Check class
class(CakeDF)



# Make a tibble
CakeT <- tibble(groupMembers = groupMembers, 
                     cakeDegrees = cakeDegrees)

# Check class
class(CakeT)



# Just like you can convert between different data types, you can convert between data structures/objects:

# Convert tibble to dataframe:
as.data.frame(CakeT)

# Convert dataframe to matrix:
as.matrix(CakeDF)

# Convert dataframe to tibble:
as_tibble(CakeDF)



# Other examples of 'as.' function for structure/object conversion
# as.data.frame()
# as.matrix()
# as.list()
# as.table()
# ...
# as_tibble()






#############





### Fundamental operations & summary statistics

# It is necessary to inspect R objects so ensure that whatever operation was performed on the object was done correctly. 
# You can simply call it and it will be printed to the console. 
# When you have a large object it is preferable to use `head()` and `tail()` to only see the first or last part of the object.
# To see the data in a tabular excel style format you can use `view()` which will open a new tap in Rstudio:


# Look at the "head" of an object, default is print first 6 lines:
head(CakeDF)
head(CakeDF, n=8)

# Look at the "tail" of an object, default is print last 6 lines:
tail(CakeDF)
tail(CakeDF, n=8)


# print (is almost always default, but there are times it is not)
print(CakeDF)

# opens table as a table, excel style
view(CakeDF)






# Another useful function is `dim()`, short for dimensions, which returns the number of rows and columns of an R object.

dim(CakeDF)







# Often we would like to pull out a single column from a dataframe or tibble to work with. This may be done with the '$' symbol:

# Extract variable with $ symbol
cakeDegrees <- CakeDF$cakeDegrees
groupMembers <- CakeDF$groupMembers




# Only interested in a specific subset of either rows or columns from an R data object?, use a 'slice'.
# A 'slice' is defined as square parentheses with the selection of rows/columns inside it. 
# 

# Specific rows/columns of an R object (a slice):
CakeDF[1:5, 1:2]

groupMembers[3:9]
groupMembers[c(1:3, 5, 9, 11)]





# Lastly, it is easy to get basic summary statistics on object in R. 
# The R-base has a variety of simple stats functions build in (i.e. no package needs to be loaded):
  

# Simple summary statistics

length(cakeDegrees)

mean(cakeDegrees)
sd(cakeDegrees)
median(cakeDegrees)

min(cakeDegrees)
max(cakeDegrees)

summary(CakeDF)
