project: 
  type: website
  output-dir: ../docs
  
website: 
  title: "FromExceltoR"
  navbar:
    left: 
      - href: index.qmd
        text: Home
  sidebar:
    style: "floating"
    contents:
      - section: "Presentations"
        contents:
          - href: Presentations/presentation1.qmd
            text: "Presentation 1: Introduction"
          - href: Presentations/presentation2.qmd
            text: "Presentation 2: Tidyverse"
          - href: Presentations/presentation4.qmd
            text: "Presentation 3: ggplot2"
            
      - section: "Exercises"
        contents:
          - href: Exercises/exercises1.qmd
            text: "Exercise 1: Introduction"
          - href: Exercises/exercises2.qmd
            text: "Exercise 2: Tidyverse"
          - href: Exercises/exercises4.qmd
            text: "Exercise 3: ggplot2"
            
      - section: "Cheat Sheets"
        contents:

format:
  html:
    theme: flatly  # You can try different themes like cosmo, flatly, etc.
    toc: true # Add "On this page"
    toc-location: right
    
    
    
