project: 
  type: website
  output-dir: ../docs
  
#title: '<img src="images/icon.png" style="vertical-align: middle; width: 150px;">FromExceltoR'
title: 'FromExceltoR'
# author: 
website: 
  title: 'FromExceltoR'
  favicon: '<img src="images/icon.png" style="vertical-align: middle; width: 150px;">'
  navbar:
    left: 
      - href: index.qmd
        text: 'Course Material'
      - href: about_heads.qmd
        text: 'About us'
        
  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
    
      # - section: "Slides"
      #   contents: 
      - href: Slideshow/FromExceltoR.pdf
        text: "Slides"
      
      - section: "Presentations"
        contents:
          - href: Presentations/presentation1.qmd
            text: "Presentation 1: Introduction"
          - href: Presentations/presentation2.qmd
            text: "Presentation 2: Tidyverse"
          - href: Presentations/presentation4.qmd
            text: "Presentation 3: ggplot2"
      
      # - section: "Data"
      #   contents: 
      - href: Presentations/data.qmd
        text: "Data"
        
      - section: "Exercises"
        contents:
          - href: Exercises/exercises1.qmd
            text: "Exercise 1: Introduction"
          - href: Exercises/exercises2.qmd
            text: "Exercise 2: Tidyverse"
          - href: Exercises/exercises4.qmd
            text: "Exercise 3: ggplot2"
      
      
      - section: "Solutions"
        contents:
          - href: Exercises/exercises2_SOLUTIONS.qmd
            text: "Exercise 2 - Solution"
          - href: Exercises/exercises4_SOLUTIONS.qmd
            text: "Exercise 3 - Solution"
            
      - section: "Cheat Sheets"
        contents:
          - href: CheatSheet/TidyverseCheatSheet.pdf
            text: "Tidyverse"
          - href: CheatSheet/ggplotCheatSheet.pdf
            text: "ggplot2"
          - href: CheatSheet/BaseRCheatSheet.pdf
            text: "Base R"

format:
  html:
    theme: flatly  # You can try different themes like cosmo, flatly, etc.
    # sidebar:
    #   collapse-level: 1
    toc: true # Add "On this page"
    toc-location: right
    
      
      
      
    
    
    
