project: 
  type: website
  output-dir: ../docs
  
website: 
  title: "FromExceltoR"
  navbar:
    left: 
      - href: index.qmd
        text: Home
  sidebar:
    style: "floating"
    contents:
      - section: "Presentations"
        contents:
          - href: Presentations/presentation1.qmd
            text: "Presentation 1: Introduction to R and Quarto"
          - href: Presentations/presentation2.qmd
            text: "Presentation 2: Tidyverse"
          - href: Presentations/presentation4.qmd
            text: "Presentation 4: Visualization with ggplot2"
            
      - section: "Exercises"
        contents:
          - href: Exercises/exercise1.qmd
            text: "Exercise 1: Introduction to R and Quarto"
          - href: Exercises/exercise2.qmd
            text: "Exercise 2: Tidyverse"
          - href: Exercises/exercise4.qmd
            text: "Presentation 4: Visualization with ggplot2"
            
      - section: "Cheat Sheets"

format:
  html:
    theme: cosmo  # You can try different themes like cosmo, flatly, etc.
    
    
    
